### ISSUE TITLE
Icon component generation is broken

### ISSUE THREAD

**Issue by maaaathis** [mittwald/flow#376]
The `build:icons` script in the components workspace is broken.

```
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1101:7)
    at Object.cwd ([...]/flow-next/.yarn/cache/fs-jetpack-npm-5.1.0-68bd17ef8a-e4961131be.zip/node_modules/fs-jetpack/lib/jetpack.js:40:44)
    at <anonymous> ([...]/flow-next/packages/components/dev/icons/fs.ts:3:27)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.10.0
```

**Comment by mfal** [comment]
@maaaathis i guess this might be an issue with you Node version.
