### ISSUE TITLE
Compiling Components should not require "unplugging" dependencies

### ISSUE THREAD

**Issue by mfal** [mittwald/flow#76]
When compiling the components package, some dependencies need to be "unplugged" in the root package.json to make things work. Otherwise compilation fails with errors like this.

```
    ✖  @mittwald/flow-components:build
       vite v5.0.6 building for production...
       transforming...
       ✓ 331 modules transformed.
       rendering chunks...

       [vite:dts] Start generate declaration files...
       computing gzip size...
       dist/style.css                          18.96 kB │ gzip:  3.13 kB
       dist/propsContext-1HT-3SRC.js            0.08 kB │ gzip:  0.09 kB
       dist/useProps-48kI4eAI.js                0.49 kB │ gzip:  0.30 kB
       dist/Label.js                            0.50 kB │ gzip:  0.31 kB
       dist/RadioGroup.js                       0.51 kB │ gzip:  0.32 kB
       dist/clsx-7d8NmkQq.js                    0.52 kB │ gzip:  0.27 kB
       dist/PropsContextProvider-FoKyLfRg.js    0.54 kB │ gzip:  0.35 kB
       dist/Text.js                             0.66 kB │ gzip:  0.38 kB
       dist/Content.js                          0.70 kB │ gzip:  0.39 kB
       dist/import-_klyNjVT.js                  0.89 kB │ gzip:  0.50 kB
       dist/Button.js                           1.09 kB │ gzip:  0.53 kB
       dist/NavigationItem.js                   1.18 kB │ gzip:  0.57 kB
       dist/Radio.js                            2.37 kB │ gzip:  0.97 kB
       dist/Navigation.js                      12.78 kB │ gzip:  3.39 kB
       dist/import-e2ZRPojs.js                 14.85 kB │ gzip:  4.99 kB
       dist/omit-UMxI0b1O.js                   30.77 kB │ gzip:  8.63 kB
       dist/real-module-Df62czfX.js            31.54 kB │ gzip:  8.54 kB
       dist/import-1GCZgtom.js                 32.27 kB │ gzip:  9.92 kB
       dist/Icon.js                           155.87 kB │ gzip: 39.60 kB
       [vite:dts] Start rollup declaration files...
       Analysis will use the bundled TypeScript version 5.0.4
       Analysis will use the bundled TypeScript version 5.0.4
       Analysis will use the bundled TypeScript version 5.0.4
       Analysis will use the bundled TypeScript version 5.0.4
       Analysis will use the bundled TypeScript version 5.0.4
       Analysis will use the bundled TypeScript version 5.0.4
       [vite:dts] ENOTDIR: not a directory, lstat '/node_modules/@react-stately/tree/dist/types.d.ts/package.json'
       ✓ built in 19.00s
       error during build:
       Error: ENOTDIR: not a directory, lstat '/node_modules/@react-stately/tree/dist/types.d.ts/package.json'
           at makeError$1 (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:30943:24)
           at ENOTDIR (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:30961:10)
           at ZipFS.resolveFilename (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:35567:15)
           at ZipFS.realpathSync (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:35358:28)
           at /Users/marcofalkenberg/dev/flow-next/.pnp.cjs:32899:102
           at /Users/marcofalkenberg/dev/flow-next/.pnp.cjs:33399:66
           at ZipOpenFS.getMountSync (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:33506:14)
           at ZipOpenFS.makeCallSync (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:33399:17)
           at ZipOpenFS.realpathSync (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:32891:17)
           at VirtualFS.realpathSync (/Users/marcofalkenberg/dev/flow-next/.pnp.cjs:33580:34)
```

**Comment by mfal** [comment]
Not an issue anymore since pnpm is used.
